{
    'name': 'HR Recruitment Agency',
    'version': '1.0',
    'summary': 'Manage recruitment agency operations from client requests to worker deployment',
    'sequence': -100,
    'description': """Recruitment Agency Management""",
    'author': 'Ibrahim Elmasry',
    'website': 'https://woledge.com',
    'category': 'Human Resources',
    'icon': 'odoo/custom_addons/ie_hr_recruitment_agency/static/description/icon.png',
    'depends': ['base', 'hr', 'sale', 'contacts'],
    'data': [
        'views/menus.xml',
        'security/ir.model.access.csv',
        'data/job_order_sequence.xml',
        'data/contract_sequence.xml',
        'views/client_views.xml',
        'views/job_order_views.xml',
        'views/worker_views.xml',
        'views/contract_views.xml',
        'views/deployment_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
